"""
Static site builder - generates HTML documentation
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional
from jinja2 import Environment, FileSystemLoader, Template


class SiteBuilder:
    """Build static HTML site from analysis data"""

    def __init__(self, output_path: Path):
        self.output_path = Path(output_path)
        self.output_path.mkdir(parents=True, exist_ok=True)

        # Setup templates
        template_dir = Path(__file__).parent / 'templates'
        self.template_env = Environment(
            loader=FileSystemLoader(str(template_dir)) if template_dir.exists() else None
        )

    def build(self, analysis: Dict, diagrams: Dict, summaries: Optional[Dict] = None):
        """
        Build complete static site

        Args:
            analysis: Analysis result from CodebaseAnalyzer
            diagrams: PlantUML diagrams from DiagramGenerator
            summaries: Optional AI summaries from AISummarizer
        """
        # Create directories
        (self.output_path / 'assets').mkdir(exist_ok=True)
        (self.output_path / 'diagrams').mkdir(exist_ok=True)

        # Save data as JSON
        data_file = self.output_path / 'data.json'
        data_file.write_text(json.dumps({
            'analysis': analysis,
            'summaries': summaries or {}
        }, indent=2), encoding='utf-8')

        # Save diagrams
        for name, source in diagrams.items():
            diagram_file = self.output_path / 'diagrams' / f'{name}.puml'
            diagram_file.write_text(source, encoding='utf-8')

        # Generate HTML
        self._generate_index(analysis, summaries)
        self._generate_files_page(analysis, summaries)
        self._generate_diagrams_page(diagrams)
        self._generate_glossary_page(analysis, summaries)
        self._generate_css()
        self._generate_js()
        self._generate_readme(analysis, diagrams, summaries)

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _detect_entry_points(self, analysis: Dict) -> list:
        """Return files that are likely CLI / run entry points."""
        ENTRY_NAMES = {'main', 'app', 'run', 'server', 'cli', 'index', 'start', '__main__'}
        project_path = analysis['project_path']
        results = []
        for f in analysis.get('files', []):
            try:
                rel = Path(f['path']).relative_to(project_path)
            except ValueError:
                rel = Path(f['path'])
            stem = Path(f['path']).stem
            has_main_fn = any(fn['name'] == 'main' for fn in f.get('functions', []))
            if stem in ENTRY_NAMES or has_main_fn:
                results.append((str(rel), f))
        return results

    def _infer_problem_statement(self, analysis: Dict) -> str:
        """Derive a one-paragraph problem statement from entry point docstrings."""
        entries = self._detect_entry_points(analysis)
        # Try module docstring of entry point first
        for _, f in entries:
            doc = f.get('docstring', '').strip()
            if doc and len(doc) > 20:
                return doc
            # Try docstring of main() function
            for fn in f.get('functions', []):
                if fn['name'] == 'main':
                    fdoc = fn.get('docstring', '').strip()
                    if fdoc and len(fdoc) > 20:
                        return fdoc
        # Fallback: synthesize from tech stack + file count
        tech = ', '.join(analysis.get('tech_stack', [])[:5])
        fc = analysis['file_count']
        name = Path(analysis['project_path']).name
        return (f"`{name}` is a {tech or 'Python'} project with {fc} source files. "
                f"This document was auto-generated by ProjWiki from static analysis "
                f"of the codebase — no AI credentials required.")

    def _build_structure_map(self, analysis: Dict) -> str:
        """Build an ASCII tree where every file gets a one-line annotation."""
        project_path = analysis['project_path']
        file_map = {}
        for f in analysis.get('files', []):
            try:
                rel = str(Path(f['path']).relative_to(project_path))
            except ValueError:
                rel = f['path']
            file_map[rel] = f

        def _annotate(f_data: Dict) -> str:
            """One-line description: docstring first line OR pub fns OR class names."""
            doc = f_data.get('docstring', '').strip()
            if doc:
                return doc.split('\n')[0][:60]
            fns = [fn['name'] for fn in f_data.get('functions', [])
                   if not fn['name'].startswith('_')][:3]
            cls = [c['name'] for c in f_data.get('classes', [])][:2]
            parts = []
            if cls:
                parts.append(', '.join(cls))
            if fns:
                parts.append(', '.join(fns) + '()')
            return ' · '.join(parts) if parts else f_data.get('extension', '') + ' file'

        def _render(node: Dict, prefix: str = '', is_last: bool = True) -> list[str]:
            connector = '└── ' if is_last else '├── '
            child_prefix = prefix + ('    ' if is_last else '│   ')
            name = node.get('name', '')
            lines = []
            if node.get('type') == 'directory':
                lines.append(f"{prefix}{connector}{name}/")
                children = node.get('children', [])
                for i, child in enumerate(children):
                    lines.extend(_render(child, child_prefix, i == len(children) - 1))
            else:
                # find annotation
                norm = name
                annotation = ''
                for rel_path, f_data in file_map.items():
                    if Path(rel_path).name == name:
                        annotation = _annotate(f_data)
                        break
                pad = max(1, 42 - len(prefix) - len(name))
                suffix = f"  # {annotation}" if annotation else ''
                lines.append(f"{prefix}{connector}{name}{' ' * pad}{suffix}")
            return lines

        structure = analysis.get('structure', {})
        root_name = structure.get('name', Path(project_path).name)
        output = [f"{root_name}/"]
        children = structure.get('children', [])
        for i, child in enumerate(children):
            output.extend(_render(child, '', i == len(children) - 1))
        return '\n'.join(output)

    def _generate_index(self, analysis: Dict, summaries: Optional[Dict]):
        """Generate main index.html"""
        project_name = Path(analysis['project_path']).name
        generated_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        overview = summaries.get('_project_overview', {}) if summaries else {}

        # Problem statement
        problem_stmt = self._infer_problem_statement(analysis)

        # Stats
        total_classes = sum(len(f.get('classes', [])) for f in analysis.get('files', []))
        total_fns    = sum(len(f.get('functions', [])) for f in analysis.get('files', []))

        # Folder structure map
        structure_map = self._build_structure_map(analysis)

        # Tech badges
        tech_badges = ''.join(
            f'<span class="badge">{tech}</span>'
            for tech in analysis.get('tech_stack', [])
        )

        # How to run
        entries = self._detect_entry_points(analysis)
        run_cards = ''
        for rel_path, f_data in entries:
            doc = f_data.get('docstring', '').strip()
            desc = doc.split('\n')[0] if doc else ''
            ext = Path(rel_path).suffix
            runner = 'python' if ext == '.py' else 'node'
            run_cards += f"""
            <div class="run-card">
                <code class="run-cmd">{runner} {rel_path}</code>
                {f'<p class="run-desc">{desc}</p>' if desc else ''}
            </div>"""
        if not run_cards:
            run_cards = '<p class="muted">No explicit entry point detected.</p>'

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name} - Documentation</title>
    <link rel="stylesheet" href="assets/style.css">
</head>
<body>
    <nav class="sidebar">
        <h2>📚 ProjWiki</h2>
        <p class="sidebar-meta">Generated<br>{generated_at}</p>
        <ul>
            <li><a href="index.html" class="active">Overview</a></li>
            <li><a href="files.html">Files</a></li>
            <li><a href="diagrams.html">Diagrams</a></li>
            <li><a href="glossary.html">Glossary</a></li>
            <li><a href="README.md">README.md ↗</a></li>
        </ul>
    </nav>

    <main class="content">
        <h1>{project_name}</h1>

        <section class="overview">
            <h2>🧩 What This Project Does</h2>
            <p>{problem_stmt}</p>
        </section>

        <section class="stats">
            <h2>📈 At a Glance</h2>
            <div class="stat-grid">
                <div class="stat-card"><h3>{analysis['file_count']}</h3><p>Files</p></div>
                <div class="stat-card"><h3>{total_classes}</h3><p>Classes</p></div>
                <div class="stat-card"><h3>{total_fns}</h3><p>Functions</p></div>
                <div class="stat-card"><h3>{len(analysis.get('tech_stack', []))}</h3><p>Technologies</p></div>
            </div>
        </section>

        <section class="structure-section">
            <h2>📁 Folder Structure</h2>
            <p class="section-hint">Every file annotated with its purpose.</p>
            <pre class="structure-map">{structure_map}</pre>
        </section>

        <section class="tech-stack">
            <h2>🔧 Tech Stack</h2>
            <div class="tech-badges">
                {tech_badges if tech_badges else '<span class="muted">None detected</span>'}
            </div>
        </section>

        <section class="how-to-run">
            <h2>▶ How to Run</h2>
            {run_cards}
        </section>

        <section class="quick-links">
            <h2>🚀 Explore</h2>
            <ul>
                <li><a href="files.html">Browse all files →</a></li>
                <li><a href="diagrams.html">View architecture diagrams →</a></li>
                <li><a href="glossary.html">Read the glossary →</a></li>
                <li><a href="README.md">Download README.md →</a></li>
            </ul>
        </section>
    </main>

    <script src="assets/main.js"></script>
</body>
</html>"""

        (self.output_path / 'index.html').write_text(html, encoding='utf-8')

    def _build_offline_summary(self, file_data: Dict) -> str:
        """Build a summary from parsed metadata when AI summaries are unavailable"""
        if file_data.get('docstring'):
            return file_data['docstring'].split('\n')[0].strip()
        classes = file_data.get('classes', [])
        functions = file_data.get('functions', [])
        parts = []
        if classes:
            names = [c['name'] for c in classes]
            parts.append(f"Defines {len(classes)} class(es): {', '.join(names)}")
        pub_fns = [f['name'] for f in functions if not f['name'].startswith('_')]
        if pub_fns:
            parts.append(f"{len(pub_fns)} public function(s): {', '.join(pub_fns[:3])}")
        return '. '.join(parts) if parts else f"{file_data.get('extension', '')} file"

    def _generate_files_page(self, analysis: Dict, summaries: Optional[Dict]):
        """Generate files.html"""
        files_html = []

        for file_data in analysis['files']:
            file_path = file_data['path']
            file_summary = summaries.get(file_path, {}) if summaries else {}
            summary_text = file_summary.get('summary') or self._build_offline_summary(file_data)

            classes = file_data.get('classes', [])
            functions = file_data.get('functions', [])

            # Classes section
            classes_html = ''
            if classes:
                items = ''
                for cls in classes:
                    methods = cls.get('methods', [])
                    all_method_names = [m['name'] if isinstance(m, dict) else m for m in methods]
                    method_str = ', '.join(all_method_names) if all_method_names else ''
                    doc = cls.get('docstring', '')
                    doc_part = f' <span class="item-doc">— {doc.split(chr(10))[0]}</span>' if doc else ''
                    method_part = f'<span class="method-list">Methods: {method_str}</span>' if method_str else ''
                    items += f'<li><span class="item-name">{cls["name"]}</span>{doc_part}<br>{method_part}</li>'
                classes_html = f'<div class="detail-section"><span class="detail-label">Classes</span><ul class="item-list">{items}</ul></div>'

            # Functions section
            functions_html = ''
            if functions:
                items = ''
                for fn in functions:
                    args = [a for a in fn.get('args', []) if a not in ('self', 'cls')]
                    args_str = f'({", ".join(args)})' if args else '()'
                    doc = fn.get('docstring', '')
                    doc_part = f' <span class="item-doc">— {doc.split(chr(10))[0]}</span>' if doc else ''
                    items += f'<li><span class="item-name">{fn["name"]}</span><span class="item-args">{args_str}</span>{doc_part}</li>'
                functions_html = f'<div class="detail-section"><span class="detail-label">Functions</span><ul class="item-list">{items}</ul></div>'

            # External imports only
            ext_imports = [i for i in file_data.get('imports', []) if not i.startswith('.')]
            imports_html = ''
            if ext_imports:
                imports_html = f'<div class="detail-section"><span class="detail-label">Imports</span><span class="import-list">{", ".join(ext_imports[:8])}</span></div>'

            detail_html = ''
            if classes_html or functions_html or imports_html:
                detail_html = f'<div class="file-detail">{classes_html}{functions_html}{imports_html}</div>'

            files_html.append(f"""
            <div class="file-card">
                <h3>{file_data['name']}</h3>
                <p class="file-path">{Path(file_path).relative_to(analysis['project_path'])}</p>
                <p class="file-summary">{summary_text}</p>
                {detail_html}
                <div class="file-meta">
                    <span>Lines: {file_data['lines']}</span>
                    <span>Classes: {len(classes)}</span>
                    <span>Functions: {len(functions)}</span>
                    <span>Imports: {len(file_data.get('imports', []))}</span>
                </div>
            </div>
            """)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Files - Documentation</title>
    <link rel="stylesheet" href="assets/style.css">
</head>
<body>
    <nav class="sidebar">
        <h2>📚 ProjWiki</h2>
        <ul>
            <li><a href="index.html">Overview</a></li>
            <li><a href="files.html" class="active">Files</a></li>
            <li><a href="diagrams.html">Diagrams</a></li>
            <li><a href="glossary.html">Glossary</a></li>
        </ul>
    </nav>

    <main class="content">
        <h1>📁 Files</h1>

        <div class="search-box">
            <input type="text" id="file-search" placeholder="Search files...">
        </div>

        <div class="files-grid">
            {''.join(files_html)}
        </div>
    </main>

    <script src="assets/main.js"></script>
</body>
</html>"""

        (self.output_path / 'files.html').write_text(html, encoding='utf-8')

    def _generate_diagrams_page(self, diagrams: Dict):
        """Generate diagrams.html — inline PlantUML source with copy button."""
        diagram_cards = []

        for i, (name, source) in enumerate(diagrams.items()):
            src_id = f'puml-{i}'
            escaped = (source
                       .replace('&', '&amp;')
                       .replace('<', '&lt;')
                       .replace('>', '&gt;'))
            diagram_cards.append(f"""
            <div class="diagram-card">
                <h3>{name.title()} Diagram</h3>
                <p class="section-hint">
                    Copy the source below → paste at
                    <a href="http://www.plantuml.com/plantuml/uml/" target="_blank">plantuml.com</a>
                    to render as PNG/SVG.
                </p>
                <div class="puml-container">
                    <div class="puml-toolbar">
                        <span class="puml-label">{name}.puml</span>
                        <button class="copy-btn" data-target="{src_id}">Copy</button>
                    </div>
                    <pre class="puml-source" id="{src_id}">{escaped}</pre>
                </div>
                <a href="diagrams/{name}.puml" class="btn btn-sm" download>⬇ Download .puml</a>
            </div>
            """)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Diagrams - Documentation</title>
    <link rel="stylesheet" href="assets/style.css">
</head>
<body>
    <nav class="sidebar">
        <h2>📚 ProjWiki</h2>
        <ul>
            <li><a href="index.html">Overview</a></li>
            <li><a href="files.html">Files</a></li>
            <li><a href="diagrams.html" class="active">Diagrams</a></li>
            <li><a href="glossary.html">Glossary</a></li>
        </ul>
    </nav>

    <main class="content">
        <h1>🔗 Architecture Diagrams</h1>
        <p class="section-hint">Generated {len(diagrams)} diagram(s). Each block shows the raw PlantUML source — copy and render online for free.</p>

        <div class="diagrams-list">
            {''.join(diagram_cards)}
        </div>
    </main>

    <script src="assets/main.js"></script>
</body>
</html>"""

        (self.output_path / 'diagrams.html').write_text(html, encoding='utf-8')

    def _generate_glossary_page(self, analysis: Dict, summaries: Optional[Dict]):
        """Generate glossary.html"""
        glossary_terms = analysis.get('glossary_terms', {})

        terms_html = []
        for term, definition in sorted(glossary_terms.items()):
            safe_def = (definition
                        .replace('&', '&amp;')
                        .replace('<', '&lt;')
                        .replace('>', '&gt;')
                        .replace('\n', '<br>'))
            terms_html.append(f"""
            <div class="glossary-term">
                <h3>{term}</h3>
                <p>{safe_def}</p>
            </div>
            """)

        content = ''.join(terms_html) if terms_html else '<p>No terms extracted from the codebase.</p>'

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Glossary - Documentation</title>
    <link rel="stylesheet" href="assets/style.css">
</head>
<body>
    <nav class="sidebar">
        <h2>📚 ProjWiki</h2>
        <ul>
            <li><a href="index.html">Overview</a></li>
            <li><a href="files.html">Files</a></li>
            <li><a href="diagrams.html">Diagrams</a></li>
            <li><a href="glossary.html" class="active">Glossary</a></li>
        </ul>
    </nav>

    <main class="content">
        <h1>📚 Glossary</h1>

        <div class="search-box">
            <input type="text" id="glossary-search" placeholder="Search terms...">
        </div>

        <div class="glossary">
            {content}
        </div>
    </main>

    <script src="assets/main.js"></script>
</body>
</html>"""

        (self.output_path / 'glossary.html').write_text(html, encoding='utf-8')

    def _generate_readme(self, analysis: Dict, diagrams: Dict, summaries: Optional[Dict]):
        """Generate README.md — structured like a real technical project README."""
        project_name = Path(analysis['project_path']).name
        generated_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        project_path = analysis['project_path']
        tech_stack = analysis.get('tech_stack', [])
        glossary_terms = analysis.get('glossary_terms', {})
        files = analysis.get('files', [])
        dependencies = analysis.get('dependencies', {})

        L = []   # lines buffer

        # ── Title ──────────────────────────────────────────────────────────
        L += [f'# {project_name}', '',
              f'> *Auto-generated by ProjWiki on {generated_at}*', '']

        # ── Problem Statement ───────────────────────────────────────────────
        L += ['## Problem Statement / What This Project Does', '']
        problem = self._infer_problem_statement(analysis)
        L += [problem, '']

        # quick stats inline
        total_classes = sum(len(f.get('classes', [])) for f in files)
        total_fns = sum(len(f.get('functions', [])) for f in files)
        L += [
            f'| Metric | Value |',
            f'|--------|-------|',
            f'| Source files | {analysis["file_count"]} |',
            f'| Classes | {total_classes} |',
            f'| Functions | {total_fns} |',
            f'| Technologies | {len(tech_stack)} |',
            f'| Diagrams | {len(diagrams)} |',
            '',
        ]

        # ── Folder Structure ────────────────────────────────────────────────
        L += ['## Folder Structure', '',
              'Every file is annotated with its purpose in one line.', '']
        structure_map = self._build_structure_map(analysis)
        L += ['```', structure_map, '```', '']

        # ── Tech Stack ──────────────────────────────────────────────────────
        if tech_stack:
            L += ['## Tech Stack', '']
            for t in tech_stack:
                L.append(f'- `{t}`')
            L.append('')

        # ── Entry Points / How to Run ────────────────────────────────────────
        entries = self._detect_entry_points(analysis)
        L += ['## Entry Points & How to Run', '']
        if entries:
            for rel_path, f_data in entries:
                doc = f_data.get('docstring', '').strip()
                desc = doc.split('\n')[0] if doc else ''
                L.append(f'**`{rel_path}`**' + (f'  — {desc}' if desc else ''))
                ext = Path(rel_path).suffix
                runner = 'python' if ext == '.py' else 'node'
                L += ['```bash', f'{runner} {rel_path}', '```', '']
        else:
            L += ['No explicit entry point detected. Check the files above for a `main()` function.', '']

        # ── Architecture Diagrams ───────────────────────────────────────────
        L += ['## Architecture Diagrams', '',
              'Paste any `.puml` block below into https://www.plantuml.com/plantuml/uml/ to render.', '']
        for name, source in diagrams.items():
            L += [f'### {name.title()} Diagram', '',
                  f'File: `diagrams/{name}.puml`', '',
                  '```plantuml', source, '```', '']

        # ── Module Dependency Map ───────────────────────────────────────────
        if dependencies:
            L += ['## Module Dependency Map', '']
            for fp_str, imports in sorted(dependencies.items()):
                try:
                    rel = Path(fp_str).relative_to(project_path)
                except ValueError:
                    rel = Path(fp_str).name
                ext_imports = [i for i in imports if not i.startswith('.')]
                rel_imports = [i for i in imports if i.startswith('.')]
                L.append(f'**`{rel}`**')
                if rel_imports:
                    L.append(f'- Internal: {", ".join(f"`{i}`" for i in rel_imports)}')
                if ext_imports:
                    L.append(f'- External: {", ".join(f"`{i}`" for i in ext_imports[:6])}')
                L.append('')

        # ── Per-file Technical Details ──────────────────────────────────────
        L += ['## File Details', '']
        for f in sorted(files, key=lambda x: x['path']):
            try:
                rel = Path(f['path']).relative_to(project_path)
            except ValueError:
                rel = Path(f['path']).name

            summary = self._build_offline_summary(f)
            L += [f'### `{rel}`', f'> {summary}', '']
            L += [
                '| | |', '|---|---|',
                f'| Lines | {f["lines"]} |',
                f'| Classes | {len(f.get("classes", []))} |',
                f'| Functions | {len(f.get("functions", []))} |',
                f'| Imports | {len(f.get("imports", []))} |', '',
            ]
            for cls in f.get('classes', []):
                doc = cls.get('docstring', '')
                doc_line = f' — {doc.split(chr(10))[0]}' if doc else ''
                L.append(f'**Class `{cls["name"]}`**{doc_line}')
                methods = cls.get('methods', [])
                pub = [m['name'] if isinstance(m, dict) else m for m in methods
                       if not (m['name'] if isinstance(m, dict) else m).startswith('_')]
                priv = [m['name'] if isinstance(m, dict) else m for m in methods
                        if (m['name'] if isinstance(m, dict) else m).startswith('_')]
                if pub:
                    L.append(f'- Public: {", ".join(f"`{m}`" for m in pub)}')
                if priv:
                    L.append(f'- Private: {", ".join(f"`{m}`" for m in priv)}')
            for fn in f.get('functions', []):
                args = [a for a in fn.get('args', []) if a not in ('self', 'cls')]
                sig = f'`{fn["name"]}({", ".join(args)})`'
                doc = fn.get('docstring', '')
                doc_line = f' — {doc.split(chr(10))[0]}' if doc else ''
                L.append(f'- {sig}{doc_line}')
            L.append('')

        # ── Glossary ─────────────────────────────────────────────────────────
        if glossary_terms:
            L += ['## Glossary', '']
            for term, definition in sorted(glossary_terms.items()):
                L.append(f'**`{term}`**')
                L.append(definition.replace('\n', '  \n'))
                L.append('')

        # ── Known Limitations ───────────────────────────────────────────────
        L += [
            '## Known Limitations', '',
            '- Parsing is Python-only at AST level; other languages show line/import counts only.',
            '- File summaries are derived from docstrings (offline). AI summaries require credentials.',
            '- PlantUML diagrams are text `.puml` files — rendering to PNG needs the `plantuml` CLI or Java.',
            '- Cyclic imports are included in diagrams but may show unexpected order.',
            '',
        ]

        # ── Future Work ──────────────────────────────────────────────────────
        L += [
            '## Future Work', '',
            '- [ ] Multi-language parsing (JavaScript/TypeScript, Java, Go)',
            '- [ ] Interactive SVG diagrams rendered in-browser',
            '- [ ] Diff mode: compare two analysis runs to show what changed',
            '- [ ] Plug-in support for other LLM providers (OpenAI, Ollama, Azure)',
            '- [ ] GitHub Action: run on every PR and post summary as comment',
            '- [ ] `projwiki.yaml` config file for per-repo ignore patterns and custom lane rules',
            '',
        ]

        (self.output_path / 'README.md').write_text('\n'.join(L), encoding='utf-8')

    def _generate_css(self):
        """Generate main CSS file"""
        css = """* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
    display: flex;
    min-height: 100vh;
    background: #f5f5f5;
}

.sidebar {
    width: 250px;
    background: #2c3e50;
    color: white;
    padding: 2rem;
    position: fixed;
    height: 100vh;
    overflow-y: auto;
}

.sidebar h2 {
    margin-bottom: 2rem;
    font-size: 1.5rem;
}

.sidebar ul {
    list-style: none;
}

.sidebar li {
    margin-bottom: 1rem;
}

.sidebar a {
    color: #ecf0f1;
    text-decoration: none;
    display: block;
    padding: 0.5rem;
    border-radius: 4px;
    transition: background 0.2s;
}

.sidebar a:hover, .sidebar a.active {
    background: #34495e;
}

.content {
    margin-left: 250px;
    padding: 3rem;
    flex: 1;
    max-width: 1200px;
}

h1 {
    font-size: 2.5rem;
    margin-bottom: 2rem;
    color: #2c3e50;
}

h2 {
    font-size: 1.8rem;
    margin: 2rem 0 1rem 0;
    color: #34495e;
}

section {
    background: white;
    padding: 2rem;
    margin-bottom: 2rem;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.stat-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 1rem;
    margin-top: 1rem;
}

.stat-card {
    text-align: center;
    padding: 1.5rem;
    background: #ecf0f1;
    border-radius: 8px;
}

.stat-card h3 {
    font-size: 2rem;
    color: #3498db;
    margin-bottom: 0.5rem;
}

.stat-card p {
    color: #7f8c8d;
}

.tech-badges {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin-top: 1rem;
}

.badge {
    background: #3498db;
    color: white;
    padding: 0.5rem 1rem;
    border-radius: 20px;
    font-size: 0.9rem;
}

.file-card, .diagram-card {
    background: white;
    padding: 1.5rem;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    margin-bottom: 1rem;
}

.file-card h3 {
    color: #2c3e50;
    margin-bottom: 0.5rem;
}

.file-path {
    color: #7f8c8d;
    font-size: 0.9rem;
    font-family: monospace;
    margin-bottom: 1rem;
}

.file-summary {
    margin-bottom: 1rem;
    line-height: 1.6;
}

.file-meta {
    display: flex;
    gap: 1rem;
    font-size: 0.85rem;
    color: #7f8c8d;
}

.search-box {
    margin-bottom: 2rem;
}

.search-box input {
    width: 100%;
    padding: 1rem;
    border: 2px solid #ecf0f1;
    border-radius: 8px;
    font-size: 1rem;
}

.search-box input:focus {
    outline: none;
    border-color: #3498db;
}

.btn {
    display: inline-block;
    background: #3498db;
    color: white;
    padding: 0.75rem 1.5rem;
    border-radius: 4px;
    text-decoration: none;
    margin-top: 1rem;
}

.btn:hover {
    background: #2980b9;
}

.note {
    margin-top: 0.5rem;
    font-size: 0.85rem;
    color: #7f8c8d;
}

.glossary pre {
    white-space: pre-wrap;
    line-height: 1.8;
    font-family: system-ui, sans-serif;
}

.file-detail {
    margin: 0.75rem 0;
    border-left: 3px solid #3498db;
    padding-left: 1rem;
}

.detail-section {
    margin-bottom: 0.6rem;
}

.detail-label {
    font-weight: bold;
    font-size: 0.78rem;
    text-transform: uppercase;
    color: #95a5a6;
    letter-spacing: 0.05em;
    display: block;
    margin-bottom: 0.25rem;
}

.item-list {
    list-style: none;
    margin: 0;
    padding: 0;
}

.item-list li {
    margin-bottom: 0.4rem;
    line-height: 1.5;
}

.item-name {
    font-family: monospace;
    font-weight: bold;
    color: #2c3e50;
}

.item-doc {
    color: #7f8c8d;
    font-size: 0.88rem;
}

.method-list {
    font-family: monospace;
    font-size: 0.8rem;
    color: #95a5a6;
    display: block;
}

.import-list {
    font-family: monospace;
    font-size: 0.85rem;
    color: #16a085;
}

.item-args {
    font-family: monospace;
    font-size: 0.85rem;
    color: #8e44ad;
}

.glossary-term {
    background: white;
    padding: 1.25rem 1.5rem;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    margin-bottom: 1rem;
    border-left: 4px solid #3498db;
}

.glossary-term h3 {
    font-family: monospace;
    color: #2c3e50;
    margin-bottom: 0.5rem;
    font-size: 1.05rem;
}

.glossary-term p {
    color: #555;
    line-height: 1.6;
    font-size: 0.95rem;
}

.quick-links ul {
    list-style: none;
}

.quick-links li {
    margin-bottom: 1rem;
}

.quick-links a {
    color: #3498db;
    text-decoration: none;
    font-size: 1.1rem;
}

.quick-links a:hover {
    text-decoration: underline;
}

/* ─── Folder-structure map ─────────────────────────────────────────────── */
.structure-map {
    background: #1e2733;
    color: #a8d8a8;
    font-family: 'Courier New', Courier, monospace;
    font-size: 0.83rem;
    line-height: 1.65;
    padding: 1.5rem 1.75rem;
    border-radius: 8px;
    overflow-x: auto;
    margin-top: 0.75rem;
    white-space: pre;
}

/* ─── Run cards ────────────────────────────────────────────────────────── */
.run-card {
    background: #f8f9fa;
    border: 1px solid #e9ecef;
    border-left: 4px solid #3498db;
    border-radius: 6px;
    padding: 1rem 1.25rem;
    margin-bottom: 0.75rem;
}

.run-cmd {
    font-family: 'Courier New', Courier, monospace;
    font-size: 0.95rem;
    background: #2c3e50;
    color: #a8d8a8;
    padding: 0.3rem 0.85rem;
    border-radius: 4px;
    display: inline-block;
}

.run-desc {
    margin-top: 0.5rem;
    color: #7f8c8d;
    font-size: 0.9rem;
}

/* ─── Sidebar meta (timestamp) ─────────────────────────────────────────── */
.sidebar-meta {
    font-size: 0.72rem;
    color: #95a5a6;
    line-height: 1.5;
    margin-bottom: 1.5rem;
    margin-top: -1rem;
}

/* ─── Section hints ────────────────────────────────────────────────────── */
.section-hint {
    font-size: 0.85rem;
    color: #95a5a6;
    margin-top: -0.25rem;
    margin-bottom: 0.75rem;
}

.section-hint a {
    color: #3498db;
}

/* ─── Muted text ───────────────────────────────────────────────────────── */
.muted {
    color: #95a5a6;
    font-style: italic;
}

/* ─── PlantUML inline viewer ───────────────────────────────────────────── */
.diagrams-list {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
}

.puml-container {
    margin: 0.75rem 0 0.5rem;
    border: 1px solid #dee2e6;
    border-radius: 6px;
    overflow: hidden;
}

.puml-toolbar {
    background: #343a40;
    color: #adb5bd;
    padding: 0.5rem 1rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 0.85rem;
}

.puml-label {
    font-family: 'Courier New', Courier, monospace;
    color: #a8d8a8;
    font-size: 0.8rem;
}

.puml-source {
    background: #1e2733;
    color: #abb2bf;
    font-family: 'Courier New', Courier, monospace;
    font-size: 0.8rem;
    line-height: 1.55;
    padding: 1.25rem 1.5rem;
    overflow-x: auto;
    max-height: 420px;
    overflow-y: auto;
    margin: 0;
    white-space: pre;
}

/* ─── Copy button ──────────────────────────────────────────────────────── */
.copy-btn {
    background: #3498db;
    color: white;
    border: none;
    padding: 0.28rem 0.8rem;
    border-radius: 4px;
    cursor: pointer;
    font-size: 0.78rem;
    transition: background 0.2s;
    font-family: inherit;
}

.copy-btn:hover {
    background: #2980b9;
}

.copy-btn.copied {
    background: #27ae60;
}

.btn-sm {
    padding: 0.4rem 0.9rem;
    font-size: 0.85rem;
    margin-top: 0.4rem;
    display: inline-block;
}
"""

        assets_dir = self.output_path / 'assets'
        assets_dir.mkdir(exist_ok=True)
        (assets_dir / 'style.css').write_text(css, encoding='utf-8')

    def _generate_js(self):
        """Generate main JavaScript file"""
        js = """// Search functionality
document.addEventListener('DOMContentLoaded', function() {
    function setupSearch(inputId, cardSelector) {
        const input = document.getElementById(inputId);
        if (!input) return;
        input.addEventListener('input', function(e) {
            const query = e.target.value.toLowerCase();
            document.querySelectorAll(cardSelector).forEach(card => {
                card.style.display = card.textContent.toLowerCase().includes(query) ? 'block' : 'none';
            });
        });
    }

    setupSearch('file-search', '.file-card');
    setupSearch('glossary-search', '.glossary-term');

    // Copy-to-clipboard for PlantUML source blocks
    document.querySelectorAll('.copy-btn').forEach(function(btn) {
        btn.addEventListener('click', function() {
            var targetId = btn.getAttribute('data-target');
            var pre = document.getElementById(targetId);
            if (!pre) return;
            var text = pre.textContent || pre.innerText;
            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(text).then(function() {
                    showCopied(btn);
                }).catch(function() {
                    fallbackCopy(text, btn);
                });
            } else {
                fallbackCopy(text, btn);
            }
        });
    });

    function showCopied(btn) {
        var orig = btn.textContent;
        btn.textContent = 'Copied!';
        btn.classList.add('copied');
        setTimeout(function() {
            btn.textContent = orig;
            btn.classList.remove('copied');
        }, 2000);
    }

    function fallbackCopy(text, btn) {
        var ta = document.createElement('textarea');
        ta.value = text;
        ta.style.position = 'fixed';
        ta.style.opacity = '0';
        document.body.appendChild(ta);
        ta.focus();
        ta.select();
        try {
            document.execCommand('copy');
            showCopied(btn);
        } catch(e) {
            btn.textContent = 'Error';
        }
        document.body.removeChild(ta);
    }
});
"""

        assets_dir = self.output_path / 'assets'
        (assets_dir / 'main.js').write_text(js, encoding='utf-8')
